// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjjTfUrqZI_94cDXrdxWVsKcznM9MklQc',
    appId: '1:387844939134:android:5e51947e9b38d267dfa72f',
    messagingSenderId: '387844939134',
    projectId: 'flutter-edutrack',
    storageBucket: 'flutter-edutrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuRS48akm7r5v-2xCbu7WOZNQwHPytb04',
    appId: '1:387844939134:ios:68d5b989f60f02f1dfa72f',
    messagingSenderId: '387844939134',
    projectId: 'flutter-edutrack',
    storageBucket: 'flutter-edutrack.firebasestorage.app',
    iosBundleId: 'com.example.eduTrackProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE98h49VXH3XiBlSHkMC23haRr1f70S20',
    appId: '1:387844939134:web:4e4850ec4d381193dfa72f',
    messagingSenderId: '387844939134',
    projectId: 'flutter-edutrack',
    authDomain: 'flutter-edutrack.firebaseapp.com',
    storageBucket: 'flutter-edutrack.firebasestorage.app',
  );

}